
BEGIN;

CREATE TABLE IF NOT EXISTS memos(
    id CHAR (7) UNIQUE NOT NULL,
    user_id CHAR (7) NOT NULL,
    color1 CHAR (8) NOT NULL,
    color2 CHAR (8) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    FOREIGN KEY (id) REFERENCES users (id) ON DELETE CASCADE
); 

COMMIT;