
BEGIN;

CREATE TABLE IF NOT EXISTS users(
    id CHAR (7) UNIQUE NOT NULL,
    uid VARCHAR (28) UNIQUE NOT NULL,
    name VARCHAR (10) UNIQUE NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
); 

COMMIT;
